TITLE_SIZE = 80
TITLE_STROKE = 4
TITLE_YPOS = TITLE_SIZE * 2
TITLE_WRAP = 18

HOST_SIZE = int(TITLE_SIZE * 2 / 3)
HOST_STROKE = int(TITLE_STROKE * 0.75)
HOST_WRAP = int(18 * 3 / 2)

LIST_SIZE = HOST_SIZE
LIST_ROW = 128
